import { NextResponse } from 'next/server';
import { supabase } from '@/lib/supabase';

export async function POST(request: Request) {
  try {
    const { task_id_human } = await request.json();

    if (!task_id_human) {
      return NextResponse.json({ error: 'Missing task_id_human' }, { status: 400 });
    }

    // 1. Get Task
    const { data: task } = await supabase
      .from('tasks')
      .select('id, title, abstract')
      .eq('id_human', task_id_human)
      .single();

    if (!task) return NextResponse.json({ error: 'Task not found' }, { status: 404 });

    // 2. Get Verified Findings
    const { data: findings } = await supabase
      .from('findings')
      .select(`
        *,
        author:agents(model_name)
      `)
      .eq('task_id', task.id)
      .eq('status', 'verified');

    // 3. Generate Markdown
    let markdown = `# ${task.title}\n\n`;
    markdown += `**Abstract:** ${task.abstract}\n\n`;
    markdown += `## Verified Findings\n\n`;

    if (!findings || findings.length === 0) {
      markdown += `*No verified findings yet. Awaiting Triple-Check Protocol completion.*\n`;
    } else {
      findings.forEach((f, idx) => {
        markdown += `### Finding ${idx + 1}: ${f.id.substring(0, 8)}\n`;
        markdown += `**Author:** ${f.author?.model_name}\n`;
        markdown += `**Status:** ${f.status}\n\n`;
        markdown += `${f.content}\n\n`;
        if (f.dataset_refs && f.dataset_refs.length > 0) {
          markdown += `**References:**\n`;
          f.dataset_refs.forEach((ref: string) => {
            markdown += `- ${ref}\n`;
          });
          markdown += `\n`;
        }
        markdown += `---\n\n`;
      });
    }

    markdown += `\n*Generated by Project Synapse Hub on ${new Date().toISOString()}*\n`;

    // 4. Return the draft
    return NextResponse.json({ 
      title: `${task_id_human}_Draft_Paper.md`,
      content: markdown 
    });
  } catch (err) {
    return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
  }
}
